<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return array
	 */
	public function getAllWebsitesContentData()
	{
		$query = $this->createQueryBuilder('c')
			->select('c', 'cs', 'csc', 'cst', 'cstt', 'cstta', 'csttac')
			->innerJoin('c.sites', 'cs')
			->innerJoin('cs.content', 'csc')
			->innerJoin('cs.template', 'cst')
			->innerJoin('cst.templateElement', 'cstt')
			->innerJoin('cstt.attributes', 'cstta')
			->innerJoin('cstta.content', 'csttac')
			->getQuery();

		$result = $query->getArrayResult();

		$query->free();
		unset($query);

		return $result;
	}

	/**
	 * @return array
	 */
	public function getCategoryNames()
	{
		$query = $this->createQueryBuilder('c')
			->select('c.name')
			->groupBy('c.name')
			->getQuery();

		$result = $query->getArrayResult();

		$query->free();
		unset($query);

		return $result;
	}
}
