<?php

namespace AppBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
	public function retrieveContent($timeInterval)
	{
		$query = $this->createQueryBuilder('c')
			->select('c')
			->where('DATE_ADD(c.lastAccessed, :timeIntervalValue, \'hour\') <= :now OR c.lastAccessed IS NULL')
			->setParameters([
				'timeIntervalValue' => $timeInterval,
				'now' => new \DateTime('now')
			])
			->getQuery();

		$result = $query->getResult();

		$query->free();
		unset($query);

		return $result;
	}

	public function findOneByContentUrl($contentUrl)
	{
		$query = $this->createQueryBuilder('c')
			->select('c')
			->where('c.url = :contentUrl')
			->setParameter('contentUrl', $contentUrl)
			->getQuery();

		$result = $query->getResult();

		$query->free();
		unset($query);

		return $result;
	}
}
