<?php

namespace AppBundle\Repository;

/**
 * SitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitesRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return array
	 */
	public function getSitesNames()
	{
		$query = $this->createQueryBuilder('s')
			->select('s.name')
			->groupBy('s.name')
			->getQuery();

		$result = $query->getArrayResult();

		$query->free();
		unset($query);

		return $result;
	}
}
