<?php

namespace AppBundle\Repository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return array
	 */
	public function getTemplateNames()
	{
		$query = $this->createQueryBuilder('t')
			->select('t.name')
			->groupBy('t.name')
			->getQuery();

		$result = $query->getArrayResult();

		$query->free();
		unset($query);

		return $result;
	}
}
