<?php

namespace AppBundle\Repository;

/**
 * TemplateElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateElementRepository extends \Doctrine\ORM\EntityRepository
{
}
