parameters:
  crawler.template_notify_outdated: 7 # in days
  crawler.time_interval: 256 # value in hours
  crawler.sleep_seconds: 900 # 15 minutes
#  crawler.proxy_ips:
#    -
#      Agent: ''
#      IP: ''