proxy:
    resource: "@ProxyBundle/Controller/"
    type:     annotation
    prefix:   /

crawler:
    resource: "@CrawlerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

content:
    type:     rest
    resource: ApiBundle\Controller\DefaultController