crawler:
    resource: "@CrawlerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

content:
    type:     rest
    resource: ApiBundle\Controller\DefaultController

test:
     type:     rest
     resource: ApiBundle\Controller\Test