proxy:
    resource: "@ProxyBundle/Controller/"
    type:     annotation
    prefix:   /admin

crawler:
    resource: "@CrawlerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    type:     annotation
    resource: '@ApiBundle/Controller/Rest/'

avanzu_admin_profile:
    path: admin/profile/{userid}/

avanzu_admin_logout:
    path: logout

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

menu_route_proxy:
    path: admin/proxy

menu_route_overview:
    path: admin

menu_route_categories:
    path: admin/categories

menu_route_sites:
    path: admin/sites

menu_route_templates:
    path: admin/templates

menu_route_template_elements:
    path: admin/templates/elements

menu_route_content:
    path: admin/content

menu_route_users:
    path: admin/users