AppBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    oneToMany:
        sites:
          targetEntity: Sites
          mappedBy: category
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\CategoryRepository
