AppBundle\Entity\Content:
    type: entity
    table: content
    indexes:
        fk_content_sites1_idx:
            columns:
                - sites_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        lastAccessed:
            type: datetime
            nullable: true
            column: last_accessed
    manyToOne:
        sites:
            targetEntity: Sites
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: sites
            joinColumns:
                sites_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        attributes:
            targetEntity: Attributes
            mappedBy: content
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\ContentRepository
