AppBundle\Entity\Sites:
    type: entity
    table: sites
    indexes:
        fk_sites_category1_idx:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mainUrl:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: main_url
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: sites
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        content:
            targetEntity: Content
            mappedBy: sites
        template:
            targetEntity: Template
            mappedBy: sites
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\SitesRepository
