AppBundle\Entity\TemplateElement:
    type: entity
    table: template_element
    indexes:
        fk_template_element_template1_idx:
            columns:
                - template_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cssPath:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
            column: css_path
    manyToOne:
        template:
            targetEntity: Template
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: templateElement
            joinColumns:
                template_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        attributes:
            targetEntity: Attributes
            mappedBy: templateElement
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\TemplateElementRepository
