AppBundle\Entity\Template:
    type: entity
    table: template
    indexes:
        fk_template_sites1_idx:
            columns:
                - sites_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        sites:
            targetEntity: Sites
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sites_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
