AppBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: true
                default: ''
    lifecycleCallbacks: {  }
    repositoryClass: AppBundle\Repository\UsersRepository
