AppBundle\Entity\UsersHasRoles:
    type: entity
    table: users_has_roles
    indexes:
        fk_users_has_roles_roles1_idx:
            columns:
                - roles_id
        fk_users_has_roles_users_idx:
            columns:
                - users_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        roles:
            targetEntity: Roles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                roles_id:
                    referencedColumnName: id
            orphanRemoval: false
        users:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                users_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
